const sindromesAsocGeneticas = [
  'Asociación CHARGE',
  'Asociación VACTER/VACTERL',
  'Distrofia de Duchenne',
  'Distrofia de Steinert',
  'Atrofia Muscular Espinal- AME',
  'Ellis-Van Creveld',
  'Enfermedad de Fabry',
  'Esclerosis Tuberosa',
  'Microdeleción 22q11 - Síndrome de Di George,',
  'Microdeleción 22q11 - Síndrome Velocardiofacial de Shprintzen',
  'Microdeleción 22q11 - CATCH22',
  'Rasopatia - Sindrome de Noonan',
  'Rasopatia - Sindrome Costello',
  'Rasopatia - Sindrome Cardio-Facio-Cutaneo',
  'Rasopatia - Neurofibromatosis 1',
  'Rasopatia - Sindrome Legius',
  'Rasopatia - Sindrome de Leopard',
  'Rasopatia - Malformación capilar – malformación artriovenosa',
  'Mucopolisacaridosis',
  'Neurofibromatosis tipo 2',
  'Síndrome de Adams-Oliver',
  'Síndrome de Kabuki',
  'Síndrome Alcohólico Fetal',
  'Síndrome Apert',
  'Síndrome Crouzon',
  'Síndrome de Alagille',
  'Síndrome de Angelman',
  'Síndrome de Beuren Williams',
  'Síndrome de Goldenhar',
  'Síndrome de Holt-Oram',
  'Síndrome de Jacobsen',
  'Síndrome de Ehlers-Danlos',
  'Síndrome de Loeys-Dietz',
  'Síndrome de Marfan',
  'Síndrome de Myhre',
  'Síndrome de Pierre Robin',
  'Síndrome de Polland',
  'Síndrome de Prader-Willi',
  'Síndrome de Turner',
  'Síndrome de Wolf-Hirschhorn',
  'Síndrome de X frágil',
  'Síndrome del maullido del gato',
  'Síndrome PHACE',
  'Síndrome Smith-Lemli-Opitz',
  'Síndrome Jerver Lange Nelsen',
  'Síndrome de Cayelr',
  'Síndrome de Cornelia Lange',
  'Trisomía 13 = Síndrome de Patau',
  'Trisomía 18 = Síndrome de Edwards',
  'Trisomía 21 = Síndrome de Down',
  'Progeria',
  'Otros (aclarar en comentarios)',
];
